name: rate_my_bistro
description: Rate your daily meal received in your local bistro
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  bubble: ^1.1.9+1
  cupertino_icons: ^0.1.0
  shared_preferences: ^0.5.6+1
  flutter_rating_bar: ^3.0.0+1
  # image_picker: ^0.6.3+1
  redux_logging: ^0.4.0
  flutter_redux: 0.6.0
  redux: 4.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
  uses-material-design: true
  assets:
    - assets/meal.png
    - assets/slanted_menu.png
    - assets/logo.png
    - assets/food/missing_picture_0.jpg
    - assets/food/missing_picture_1.jpg
    - assets/food/missing_picture_2.jpg
    - assets/food/missing_picture_3.jpg
    - assets/food/missing_picture_4.jpg
    - assets/food/missing_picture_5.jpg

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"